import Nav from '../../components/Nav.jsx';
import '../../components/Nav.css';
import Main from '../../components/Main.jsx';
import Footer from '../../components/Footer.jsx';
import '../../components/Footer.css';
import Contact from '../../components/Contact.jsx';
import '../../components/Contact.css';
import HomeHeader from '../../components/HomeHeader.jsx';
import '../../components/HomeHeader.css';
import Product from '../../components/Product.jsx';
import '../../components/Product.css';
import ProductSection from '../../components/ProductSection.jsx';
import '../../components/ProductSection.css';
export { Nav, Main, Footer, Contact, HomeHeader, Product, ProductSection };